services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - "40010:9000"
    volumes:
      - .:/var/www
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.7"
        reservations:
          memory: 256M
